package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * app service = new app();
 * AppSoap portType = service.getAppSoap();
 * portType.getUser(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "app", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://appservices.chinatsi.com/app.asmx?wsdl")
public class App extends Service {

	private final static URL APP_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(org.tempuri.App.class
			.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.tempuri.App.class.getResource(".");
			url = new URL(baseUrl,
					"http://appservices.chinatsi.com/app.asmx?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://appservices.chinatsi.com/app.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		APP_WSDL_LOCATION = url;
	}

	public App(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public App() {
		super(APP_WSDL_LOCATION, new QName("http://tempuri.org/", "app"));
	}

	/**
	 * 
	 * @return returns AppSoap
	 */
	@WebEndpoint(name = "appSoap")
	public AppSoap getAppSoap() {
		return super.getPort(new QName("http://tempuri.org/", "appSoap"),
				AppSoap.class);
	}

	/**
	 * 
	 * @return returns AppSoap
	 */
	@WebEndpoint(name = "appSoap12")
	public AppSoap getAppSoap12() {
		return super.getPort(new QName("http://tempuri.org/", "appSoap12"),
				AppSoap.class);
	}

}
