package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "appSoap", targetNamespace = "http://tempuri.org/")
public interface AppSoap {

	/**
	 * 
	 * @param uid
	 * @return returns org.tempuri.UserInfo
	 */
	@WebMethod(operationName = "GetUser", action = "http://tempuri.org/GetUser")
	@WebResult(name = "GetUserResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetUser", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUser")
	@ResponseWrapper(localName = "GetUserResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUserResponse")
	public UserInfo getUser(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid);

	/**
	 * 
	 * @param uid
	 * @param birthday
	 * @param sex
	 * @param username
	 * @param email
	 * @param profession
	 * @param corporation
	 * @return returns org.tempuri.CM
	 */
	@WebMethod(operationName = "EditUser", action = "http://tempuri.org/EditUser")
	@WebResult(name = "EditUserResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "EditUser", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditUser")
	@ResponseWrapper(localName = "EditUserResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EditUserResponse")
	public CM editUser(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "username", targetNamespace = "http://tempuri.org/") String username,
			@WebParam(name = "birthday", targetNamespace = "http://tempuri.org/") String birthday,
			@WebParam(name = "sex", targetNamespace = "http://tempuri.org/") String sex,
			@WebParam(name = "corporation", targetNamespace = "http://tempuri.org/") String corporation,
			@WebParam(name = "profession", targetNamespace = "http://tempuri.org/") String profession,
			@WebParam(name = "email", targetNamespace = "http://tempuri.org/") String email);

	/**
	 * 
	 * @param newpwd
	 * @param uid
	 * @param oldpwd
	 * @return returns org.tempuri.CM
	 */
	@WebMethod(operationName = "ChangPwd", action = "http://tempuri.org/ChangPwd")
	@WebResult(name = "ChangPwdResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "ChangPwd", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangPwd")
	@ResponseWrapper(localName = "ChangPwdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangPwdResponse")
	public CM changPwd(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "oldpwd", targetNamespace = "http://tempuri.org/") String oldpwd,
			@WebParam(name = "newpwd", targetNamespace = "http://tempuri.org/") String newpwd);

	/**
	 * 
	 * @param mobile
	 * @return returns org.tempuri.CMD
	 */
	@WebMethod(operationName = "VerifyTel", action = "http://tempuri.org/VerifyTel")
	@WebResult(name = "VerifyTelResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "VerifyTel", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VerifyTel")
	@ResponseWrapper(localName = "VerifyTelResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.VerifyTelResponse")
	public CMD verifyTel(
			@WebParam(name = "mobile", targetNamespace = "http://tempuri.org/") String mobile);

	/**
	 * 
	 * @param pwd
	 * @param mobile
	 * @return returns org.tempuri.LoginUser
	 */
	@WebMethod(operationName = "Login", action = "http://tempuri.org/Login")
	@WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Login")
	@ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginResponse")
	public LoginUser login(
			@WebParam(name = "mobile", targetNamespace = "http://tempuri.org/") String mobile,
			@WebParam(name = "pwd", targetNamespace = "http://tempuri.org/") String pwd);

	/**
	 * 
	 * @param pwd
	 * @param mobile
	 * @return returns org.tempuri.LoginUser
	 */
	@WebMethod(operationName = "Regist", action = "http://tempuri.org/Regist")
	@WebResult(name = "RegistResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "Regist", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Regist")
	@ResponseWrapper(localName = "RegistResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RegistResponse")
	public LoginUser regist(
			@WebParam(name = "mobile", targetNamespace = "http://tempuri.org/") String mobile,
			@WebParam(name = "pwd", targetNamespace = "http://tempuri.org/") String pwd);

	/**
	 * 
	 * @param uid
	 * @return returns org.tempuri.DxPzInfo
	 */
	@WebMethod(operationName = "GetClass1", action = "http://tempuri.org/GetClass1")
	@WebResult(name = "GetClass1Result", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetClass1", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetClass1")
	@ResponseWrapper(localName = "GetClass1Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetClass1Response")
	public DxPzInfo getClass1(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid);

	/**
	 * 
	 * @param uid
	 * @param pages
	 * @param pageNum
	 * @param classid
	 * @return returns org.tempuri.Dxmsglist
	 */
	@WebMethod(operationName = "GetSteelMsgList", action = "http://tempuri.org/GetSteelMsgList")
	@WebResult(name = "GetSteelMsgListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetSteelMsgList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSteelMsgList")
	@ResponseWrapper(localName = "GetSteelMsgListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSteelMsgListResponse")
	public Dxmsglist getSteelMsgList(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "classid", targetNamespace = "http://tempuri.org/") String classid,
			@WebParam(name = "pages", targetNamespace = "http://tempuri.org/") String pages,
			@WebParam(name = "pageNum", targetNamespace = "http://tempuri.org/") String pageNum);

	/**
	 * 
	 * @param uid
	 * @param levels
	 * @param classid
	 * @return returns org.tempuri.DxPzInfo
	 */
	@WebMethod(operationName = "GetClass", action = "http://tempuri.org/GetClass")
	@WebResult(name = "GetClassResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetClass", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetClass")
	@ResponseWrapper(localName = "GetClassResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetClassResponse")
	public DxPzInfo getClass(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "classid", targetNamespace = "http://tempuri.org/") String classid,
			@WebParam(name = "levels", targetNamespace = "http://tempuri.org/") String levels);

	/**
	 * 
	 * @param uid
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetClassAll", action = "http://tempuri.org/GetClassAll")
	@WebResult(name = "GetClassAllResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetClassAll", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetClassAll")
	@ResponseWrapper(localName = "GetClassAllResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetClassAllResponse")
	public String getClassAll(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid);

	/**
	 * 
	 * @param uid
	 * @param sid
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SaveClass", action = "http://tempuri.org/SaveClass")
	@WebResult(name = "SaveClassResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SaveClass", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveClass")
	@ResponseWrapper(localName = "SaveClassResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveClassResponse")
	public String saveClass(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "sid", targetNamespace = "http://tempuri.org/") String sid);

	/**
	 * 
	 * @param uid
	 * @param arrclassid
	 * @return returns org.tempuri.CM
	 */
	@WebMethod(operationName = "SetDzClass", action = "http://tempuri.org/SetDzClass")
	@WebResult(name = "SetDzClassResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetDzClass", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetDzClass")
	@ResponseWrapper(localName = "SetDzClassResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetDzClassResponse")
	public CM setDzClass(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "arrclassid", targetNamespace = "http://tempuri.org/") String arrclassid);

	/**
	 * 
	 * @param uid
	 * @param infoid
	 * @return returns org.tempuri.CM
	 */
	@WebMethod(operationName = "DelSteelMsg", action = "http://tempuri.org/DelSteelMsg")
	@WebResult(name = "DelSteelMsgResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "DelSteelMsg", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DelSteelMsg")
	@ResponseWrapper(localName = "DelSteelMsgResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DelSteelMsgResponse")
	public CM delSteelMsg(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "infoid", targetNamespace = "http://tempuri.org/") String infoid);

	/**
	 * 
	 * @param classid
	 * @return returns org.tempuri.InfoPic
	 */
	@WebMethod(operationName = "GetPicInfo", action = "http://tempuri.org/GetPicInfo")
	@WebResult(name = "GetPicInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetPicInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPicInfo")
	@ResponseWrapper(localName = "GetPicInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPicInfoResponse")
	public InfoPic getPicInfo(
			@WebParam(name = "classid", targetNamespace = "http://tempuri.org/") String classid);

	/**
	 * 
	 * @param uid
	 * @param pages
	 * @param pageNum
	 * @param classid
	 * @return returns org.tempuri.InfoList
	 */
	@WebMethod(operationName = "GetInfoList", action = "http://tempuri.org/GetInfoList")
	@WebResult(name = "GetInfoListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetInfoList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInfoList")
	@ResponseWrapper(localName = "GetInfoListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInfoListResponse")
	public InfoList getInfoList(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "classid", targetNamespace = "http://tempuri.org/") String classid,
			@WebParam(name = "pages", targetNamespace = "http://tempuri.org/") String pages,
			@WebParam(name = "pageNum", targetNamespace = "http://tempuri.org/") String pageNum);

	/**
	 * 
	 * @param uid
	 * @param id
	 * @return returns org.tempuri.Info
	 */
	@WebMethod(operationName = "GetInfo", action = "http://tempuri.org/GetInfo")
	@WebResult(name = "GetInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInfo")
	@ResponseWrapper(localName = "GetInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInfoResponse")
	public Info getInfo(
			@WebParam(name = "id", targetNamespace = "http://tempuri.org/") String id,
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid);

	/**
	 * 
	 * @param content
	 * @param uid
	 * @param infoid
	 * @param typeid
	 * @return returns org.tempuri.CMD
	 */
	@WebMethod(operationName = "SetReply", action = "http://tempuri.org/SetReply")
	@WebResult(name = "SetReplyResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetReply", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetReply")
	@ResponseWrapper(localName = "SetReplyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetReplyResponse")
	public CMD setReply(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "typeid", targetNamespace = "http://tempuri.org/") String typeid,
			@WebParam(name = "infoid", targetNamespace = "http://tempuri.org/") String infoid,
			@WebParam(name = "content", targetNamespace = "http://tempuri.org/") String content);

	/**
	 * 
	 * @param uid
	 * @param infoid
	 * @param typeid
	 * @return returns org.tempuri.Reply
	 */
	@WebMethod(operationName = "GetReply", action = "http://tempuri.org/GetReply")
	@WebResult(name = "GetReplyResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetReply", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetReply")
	@ResponseWrapper(localName = "GetReplyResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetReplyResponse")
	public Reply getReply(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "typeid", targetNamespace = "http://tempuri.org/") String typeid,
			@WebParam(name = "infoid", targetNamespace = "http://tempuri.org/") String infoid);

	/**
	 * 
	 * @param uid
	 * @param infoid
	 * @param classid
	 * @return returns org.tempuri.CM
	 */
	@WebMethod(operationName = "SetKeep", action = "http://tempuri.org/SetKeep")
	@WebResult(name = "SetKeepResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetKeep", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetKeep")
	@ResponseWrapper(localName = "SetKeepResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetKeepResponse")
	public CM setKeep(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "classid", targetNamespace = "http://tempuri.org/") String classid,
			@WebParam(name = "infoid", targetNamespace = "http://tempuri.org/") String infoid);

	/**
	 * 
	 * @param uid
	 * @param infoid
	 * @param classid
	 * @return returns org.tempuri.CM
	 */
	@WebMethod(operationName = "CancelKeep", action = "http://tempuri.org/CancelKeep")
	@WebResult(name = "CancelKeepResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "CancelKeep", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelKeep")
	@ResponseWrapper(localName = "CancelKeepResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelKeepResponse")
	public CM cancelKeep(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "classid", targetNamespace = "http://tempuri.org/") String classid,
			@WebParam(name = "infoid", targetNamespace = "http://tempuri.org/") String infoid);

	/**
	 * 
	 * @param uid
	 * @return returns org.tempuri.KeepCount
	 */
	@WebMethod(operationName = "GetKeepCount", action = "http://tempuri.org/GetKeepCount")
	@WebResult(name = "GetKeepCountResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetKeepCount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetKeepCount")
	@ResponseWrapper(localName = "GetKeepCountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetKeepCountResponse")
	public KeepCount getKeepCount(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid);

	/**
	 * 
	 * @param uid
	 * @param pages
	 * @param pageNum
	 * @return returns org.tempuri.Dxmsglist
	 */
	@WebMethod(operationName = "GetSteelKeepList", action = "http://tempuri.org/GetSteelKeepList")
	@WebResult(name = "GetSteelKeepListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetSteelKeepList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSteelKeepList")
	@ResponseWrapper(localName = "GetSteelKeepListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSteelKeepListResponse")
	public Dxmsglist getSteelKeepList(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "pages", targetNamespace = "http://tempuri.org/") String pages,
			@WebParam(name = "pageNum", targetNamespace = "http://tempuri.org/") String pageNum);

	/**
	 * 
	 * @param uid
	 * @param pages
	 * @param pageNum
	 * @param classid
	 * @return returns org.tempuri.InfoList
	 */
	@WebMethod(operationName = "GetInfoKeepList", action = "http://tempuri.org/GetInfoKeepList")
	@WebResult(name = "GetInfoKeepListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetInfoKeepList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInfoKeepList")
	@ResponseWrapper(localName = "GetInfoKeepListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetInfoKeepListResponse")
	public InfoList getInfoKeepList(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "classid", targetNamespace = "http://tempuri.org/") String classid,
			@WebParam(name = "pages", targetNamespace = "http://tempuri.org/") String pages,
			@WebParam(name = "pageNum", targetNamespace = "http://tempuri.org/") String pageNum);

	/**
	 * 
	 * @param uid
	 * @return returns org.tempuri.UnReadNumList
	 */
	@WebMethod(operationName = "GetUnReadCount", action = "http://tempuri.org/GetUnReadCount")
	@WebResult(name = "GetUnReadCountResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetUnReadCount", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUnReadCount")
	@ResponseWrapper(localName = "GetUnReadCountResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUnReadCountResponse")
	public UnReadNumList getUnReadCount(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid);

	/**
	 * 
	 * @param infoid
	 * @return returns org.tempuri.Adlist
	 */
	@WebMethod(operationName = "GetAd1", action = "http://tempuri.org/GetAd1")
	@WebResult(name = "GetAd1Result", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetAd1", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAd1")
	@ResponseWrapper(localName = "GetAd1Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAd1Response")
	public Adlist getAd1(
			@WebParam(name = "infoid", targetNamespace = "http://tempuri.org/") String infoid);

	/**
	 * 
	 * @param classid
	 * @return returns org.tempuri.Adlist
	 */
	@WebMethod(operationName = "GetAd", action = "http://tempuri.org/GetAd")
	@WebResult(name = "GetAdResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetAd", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAd")
	@ResponseWrapper(localName = "GetAdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAdResponse")
	public Adlist getAd(
			@WebParam(name = "classid", targetNamespace = "http://tempuri.org/") String classid);

	/**
	 * 
	 * @param uid
	 * @param info
	 * @return returns org.tempuri.CM
	 */
	@WebMethod(operationName = "SetOpinion", action = "http://tempuri.org/SetOpinion")
	@WebResult(name = "SetOpinionResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SetOpinion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetOpinion")
	@ResponseWrapper(localName = "SetOpinionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetOpinionResponse")
	public CM setOpinion(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "info", targetNamespace = "http://tempuri.org/") String info);

	/**
	 * 
	 * @param uid
	 * @param pages
	 * @param pageNum
	 * @return returns org.tempuri.InfoList
	 */
	@WebMethod(operationName = "GetTsServiceList", action = "http://tempuri.org/GetTsServiceList")
	@WebResult(name = "GetTsServiceListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetTsServiceList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTsServiceList")
	@ResponseWrapper(localName = "GetTsServiceListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTsServiceListResponse")
	public InfoList getTsServiceList(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "pages", targetNamespace = "http://tempuri.org/") String pages,
			@WebParam(name = "pageNum", targetNamespace = "http://tempuri.org/") String pageNum);

	/**
	 * 
	 * @return returns org.tempuri.InfoPic
	 */
	@WebMethod(operationName = "GetTsServiceThumbPic", action = "http://tempuri.org/GetTsServiceThumbPic")
	@WebResult(name = "GetTsServiceThumbPicResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetTsServiceThumbPic", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTsServiceThumbPic")
	@ResponseWrapper(localName = "GetTsServiceThumbPicResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTsServiceThumbPicResponse")
	public InfoPic getTsServiceThumbPic();

	/**
	 * 
	 * @param uid
	 * @param id
	 * @return returns org.tempuri.Info
	 */
	@WebMethod(operationName = "GetTsServiceInfo", action = "http://tempuri.org/GetTsServiceInfo")
	@WebResult(name = "GetTsServiceInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetTsServiceInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTsServiceInfo")
	@ResponseWrapper(localName = "GetTsServiceInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTsServiceInfoResponse")
	public Info getTsServiceInfo(
			@WebParam(name = "id", targetNamespace = "http://tempuri.org/") String id,
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid);

	/**
	 * 
	 * @return returns org.tempuri.CMD
	 */
	@WebMethod(operationName = "GetTsNoticeTime", action = "http://tempuri.org/GetTsNoticeTime")
	@WebResult(name = "GetTsNoticeTimeResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetTsNoticeTime", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTsNoticeTime")
	@ResponseWrapper(localName = "GetTsNoticeTimeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTsNoticeTimeResponse")
	public CMD getTsNoticeTime();

	/**
	 * 
	 * @param uid
	 * @param pages
	 * @param pageNum
	 * @return returns org.tempuri.InfoList
	 */
	@WebMethod(operationName = "GetTsNoticeList", action = "http://tempuri.org/GetTsNoticeList")
	@WebResult(name = "GetTsNoticeListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetTsNoticeList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTsNoticeList")
	@ResponseWrapper(localName = "GetTsNoticeListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTsNoticeListResponse")
	public InfoList getTsNoticeList(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "pages", targetNamespace = "http://tempuri.org/") String pages,
			@WebParam(name = "pageNum", targetNamespace = "http://tempuri.org/") String pageNum);

	/**
	 * 
	 * @param uid
	 * @param id
	 * @return returns org.tempuri.Info
	 */
	@WebMethod(operationName = "GetTsNoticeInfo", action = "http://tempuri.org/GetTsNoticeInfo")
	@WebResult(name = "GetTsNoticeInfoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetTsNoticeInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTsNoticeInfo")
	@ResponseWrapper(localName = "GetTsNoticeInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTsNoticeInfoResponse")
	public Info getTsNoticeInfo(
			@WebParam(name = "id", targetNamespace = "http://tempuri.org/") String id,
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid);

	/**
	 * 
	 * @param uid
	 * @return returns org.tempuri.CMD
	 */
	@WebMethod(operationName = "GetTsServiceNum", action = "http://tempuri.org/GetTsServiceNum")
	@WebResult(name = "GetTsServiceNumResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetTsServiceNum", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTsServiceNum")
	@ResponseWrapper(localName = "GetTsServiceNumResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTsServiceNumResponse")
	public CMD getTsServiceNum(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid);

	/**
	 * 
	 * @param uid
	 * @param pages
	 * @param keyword
	 * @param pageNum
	 * @param classid
	 * @return returns org.tempuri.Dxmsglist
	 */
	@WebMethod(operationName = "GetSearchSteelMsgList", action = "http://tempuri.org/GetSearchSteelMsgList")
	@WebResult(name = "GetSearchSteelMsgListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetSearchSteelMsgList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSearchSteelMsgList")
	@ResponseWrapper(localName = "GetSearchSteelMsgListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSearchSteelMsgListResponse")
	public Dxmsglist getSearchSteelMsgList(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "classid", targetNamespace = "http://tempuri.org/") String classid,
			@WebParam(name = "keyword", targetNamespace = "http://tempuri.org/") String keyword,
			@WebParam(name = "pages", targetNamespace = "http://tempuri.org/") String pages,
			@WebParam(name = "pageNum", targetNamespace = "http://tempuri.org/") String pageNum);

	/**
	 * 
	 * @param uid
	 * @param pages
	 * @param keyword
	 * @param pageNum
	 * @param classid
	 * @return returns org.tempuri.Dxmsglist
	 */
	@WebMethod(operationName = "GetSearchInfoList", action = "http://tempuri.org/GetSearchInfoList")
	@WebResult(name = "GetSearchInfoListResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetSearchInfoList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSearchInfoList")
	@ResponseWrapper(localName = "GetSearchInfoListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSearchInfoListResponse")
	public Dxmsglist getSearchInfoList(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid,
			@WebParam(name = "classid", targetNamespace = "http://tempuri.org/") String classid,
			@WebParam(name = "keyword", targetNamespace = "http://tempuri.org/") String keyword,
			@WebParam(name = "pages", targetNamespace = "http://tempuri.org/") String pages,
			@WebParam(name = "pageNum", targetNamespace = "http://tempuri.org/") String pageNum);

	/**
	 * 
	 * @param uid
	 * @return returns org.tempuri.CMD
	 */
	@WebMethod(operationName = "GetSteelMsgDzClass", action = "http://tempuri.org/GetSteelMsgDzClass")
	@WebResult(name = "GetSteelMsgDzClassResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetSteelMsgDzClass", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSteelMsgDzClass")
	@ResponseWrapper(localName = "GetSteelMsgDzClassResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSteelMsgDzClassResponse")
	public CMD getSteelMsgDzClass(
			@WebParam(name = "uid", targetNamespace = "http://tempuri.org/") String uid);

	/**
	 * 
	 * @param id
	 * @return returns org.tempuri.CMD
	 */
	@WebMethod(operationName = "GetUpdate", action = "http://tempuri.org/GetUpdate")
	@WebResult(name = "GetUpdateResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetUpdate", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUpdate")
	@ResponseWrapper(localName = "GetUpdateResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUpdateResponse")
	public CMD getUpdate(
			@WebParam(name = "id", targetNamespace = "http://tempuri.org/") String id);

}
